version: "3.7"

services:

  web:
    build: .
    image: calini/draco-web:dev
    ports:
      - "3000:80"
    links:
      - backend
    volumes:
      - ./deploy/docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf

  backend:
    image: calini/draco:dev
