version: "3.7"

services:

  web:
    build: .
    image: calini/draco-web:dev
    ports:
      - "3000:80"
    links:
      - backend

  backend:
    image: calini/draco:dev
    ports:
      - "8080:8080"
