replicaCount: 1
maxSurge: 1
maxUnavailable: 0

image:
  repository: docker.io/calini/draco-web
  tag: dev
  pullPolicy: Always

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: draco.dev.ilie.io
      paths: [/]

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
